<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JenisRetribusiSeeder extends Seeder
{
    public function run()
    {
        $jenisretribusi = [
            ['id' => 54, 'kd_rekening' => '41203001', 'nm_retribusi' => 'Retribusi Bill Hotel', 'dasar_hukum_pengenaan' => 'Perda No.09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => null, 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 53, 'kd_rekening' => '4120310', 'nm_retribusi' => 'Retribusi Pertandingan Olah Raga', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => null, 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 56, 'kd_rekening' => '41202311', 'nm_retribusi' => 'Retribusi TPHS', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 57, 'kd_rekening' => '41202312', 'nm_retribusi' => 'Retribusi Sewa kandang', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 58, 'kd_rekening' => '4120233', 'nm_retribusi' => 'Retribusi Pemotongan Domba/Kambing', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 62, 'kd_rekening' => '41201053', 'nm_retribusi' => 'Retribusi Pemeriksaan Fungsi Ginjal', 'dasar_hukum_pengenaan' => 'Perwal No. 37 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 52, 'kd_rekening' => '4120302', 'nm_retribusi' => 'Retribusi Bill Restoran', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => null, 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 89, 'kd_rekening' => '4120108', 'nm_retribusi' => 'Retribusi Layanan Jasa pemeriksaan untuk maksud Tertentu', 'dasar_hukum_pengenaan' => 'Perda No.11 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 86, 'kd_rekening' => '4120218', 'nm_retribusi' => 'Retribusi Terminal - Angkot', 'dasar_hukum_pengenaan' => 'Perda No. 17 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 82, 'kd_rekening' => '4120214', 'nm_retribusi' => 'Retribusi Terminal - Tempat Usaha', 'dasar_hukum_pengenaan' => 'Perda No. 17 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 83, 'kd_rekening' => '4120215', 'nm_retribusi' => 'Retribusi Terminal - Elf', 'dasar_hukum_pengenaan' => 'Perda No. 17 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 84, 'kd_rekening' => '4120216', 'nm_retribusi' => 'Retribusi Terminal - Bus Kota Ekonomi', 'dasar_hukum_pengenaan' => 'Perda No. 17 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 90, 'kd_rekening' => '4120109', 'nm_retribusi' => 'Retribusi Jasa Tindakan Medis', 'dasar_hukum_pengenaan' => 'Perda No.11 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 92, 'kd_rekening' => '4120111', 'nm_retribusi' => 'Jasa Pemeriksaan untuk Persyaratan PNS', 'dasar_hukum_pengenaan' => 'Perda No.11 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 88, 'kd_rekening' => '4120226', 'nm_retribusi' => 'Retribusi Parkir Inap', 'dasar_hukum_pengenaan' => 'Perda No.09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 94, 'kd_rekening' => '4120113', 'nm_retribusi' => 'Pelayanan Gigi di Puskesmas', 'dasar_hukum_pengenaan' => 'Perda No.11 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 95, 'kd_rekening' => '4120114', 'nm_retribusi' => 'Rawat Inap perhari', 'dasar_hukum_pengenaan' => 'Perda No.11 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 96, 'kd_rekening' => '4120115', 'nm_retribusi' => 'Pemeriksaan Limbah Cair Rumah Sakit', 'dasar_hukum_pengenaan' => 'Perwal No. 37 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 97, 'kd_rekening' => '4120116', 'nm_retribusi' => 'Pemeriksaan Air Kolam', 'dasar_hukum_pengenaan' => 'Perwal No. 37 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 99, 'kd_rekening' => '4120121', 'nm_retribusi' => 'Persalinan Dokter Umum', 'dasar_hukum_pengenaan' => 'Perda No.11 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 100, 'kd_rekening' => '4120122', 'nm_retribusi' => 'Pemeriksaan Kimia Fisika Air Bersih, Kimia Fisika Air Minum', 'dasar_hukum_pengenaan' => 'Perwal No. 37 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => null, 'lv_kategori' => null, 'sub_kategori' => null, 'kode_kategori' => null],
            ['id' => 87, 'kd_rekening' => '41203003', 'nm_retribusi' => 'Retribusi Bill Hiburan', 'dasar_hukum_pengenaan' => 'Perda No.09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 102, 'kd_rekening' => '4120205', 'nm_retribusi' => 'Retribusi Pemakaian Kekayaan Daerah - Kendaraan Bermotor (crane)', 'dasar_hukum_pengenaan' => 'perda 09 tahun 2012', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 103, 'kd_rekening' => '4120150', 'nm_retribusi' => 'Retribusi Pengujian LAB', 'dasar_hukum_pengenaan' => 'perda 09 tahun 2012', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 104, 'kd_rekening' => '4120202', 'nm_retribusi' => 'Retribusi Pemakaian Kekayaan Daerah - Sewa Panggung Reklame', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 85, 'kd_rekening' => '4120217', 'nm_retribusi' => 'Retribusi Terminal - AKAP/AKDP Ekonomi', 'dasar_hukum_pengenaan' => 'Perda No. 17 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 109, 'kd_rekening' => '41202171', 'nm_retribusi' => 'Retribusi Terminal - AKAP/AKDP Non Ekonomi', 'dasar_hukum_pengenaan' => 'Perda Perda No. 17 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 110, 'kd_rekening' => '41202161', 'nm_retribusi' => 'Retribusi Terminal - Bus Kota Non Ekonomi', 'dasar_hukum_pengenaan' => 'Perda No. 17 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 111, 'kd_rekening' => '4120219', 'nm_retribusi' => 'Retribusi Terminal - Mobil Penumpang Pribadi / Pickup', 'dasar_hukum_pengenaan' => 'Perda No. 17 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 108, 'kd_rekening' => '4120206', 'nm_retribusi' => 'Retribusi Pemakaian Kekayaan Daerah - PSU Terminal Dishub', 'dasar_hukum_pengenaan' => 'Perwal nomor 05 tahun 2020', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 98, 'kd_rekening' => '4120123', 'nm_retribusi' => 'Persalinan Spontan Bidan', 'dasar_hukum_pengenaan' => 'Perda No.11 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 114, 'kd_rekening' => '41201193', 'nm_retribusi' => 'Retribusi Pelayanan Parkir Di Tepi Jalan Umum (Bus, Truck dan Sejenisnya))', 'dasar_hukum_pengenaan' => 'Perda nomor 10 tahun 2020', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '401'],
            ['id' => 1, 'kd_rekening' => '41201', 'nm_retribusi' => 'Retribusi Jasa Umum', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '0', 'non_karcis' => '0', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => '1', 'sub_kategori' => NULL, 'kode_kategori' => '790'],
            ['id' => 101, 'kd_rekening' => '4120306', 'nm_retribusi' => 'Izin Trayek Lintas Daerah Perpanjangan Kartu Pengawasan', 'dasar_hukum_pengenaan' => 'Perda No. 10 Tahun 2012', 'item' => '0', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '3'],
            ['id' => 2, 'kd_rekening' => '4120101', 'nm_retribusi' => 'Retribusi Pelayanan Kesehatan - Puskesmas', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '101'],
            ['id' => 59, 'kd_rekening' => '41201991', 'nm_retribusi' => 'Retribusi Parkir Pasar', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '401'],
            ['id' => 6, 'kd_rekening' => '4120105', 'nm_retribusi' => 'Retribusi Pelayanan Kesehatan - Laboratorium Kesehatan Masyarakat / Labkesda', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '0', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '201'],
            ['id' => 10, 'kd_rekening' => '4120118', 'nm_retribusi' => 'Retribusi Sewa Tempat Pemakaman atau Pembakaran / Pengabuan Mayat', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '118'],
            ['id' => 11, 'kd_rekening' => '4120119', 'nm_retribusi' => 'Retribusi Pelayanan Parkir Di Tepi Jalan Umum', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '401'],
            ['id' => 27, 'kd_rekening' => '41203', 'nm_retribusi' => 'Retribusi Perizinan Tertentu', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '0', 'non_karcis' => '0', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 45, 'lv_kategori' => '3', 'sub_kategori' => NULL, 'kode_kategori' => '792'],
            ['id' => 51, 'kd_rekening' => '4120312', 'nm_retribusi' => 'Retribusi Pemberian Perpanjangan IMTA', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => NULL, 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 55, 'kd_rekening' => '4120120', 'nm_retribusi' => 'Retribusi Pelayanan Pasar', 'dasar_hukum_pengenaan' => 'Perda No.09 Tahun 2012', 'item' => '1', 'non_karcis' => '1', 'karcis' => '1', 'denda' => NULL, 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '503'],
            ['id' => 91, 'kd_rekening' => '4120110', 'nm_retribusi' => 'Retribusi Pemeriksaan Laboratorium', 'dasar_hukum_pengenaan' => 'Perda No.11 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '105'],
            ['id' => 107, 'kd_rekening' => '41203011', 'nm_retribusi' => 'Persetujuan Bangunan Gedung', 'dasar_hukum_pengenaan' => 'Perda No.01 tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 45, 'lv_kategori' => NULL, 'sub_kategori' => '3', 'kode_kategori' => '301'],
            ['id' => 50, 'kd_rekening' => '4120152', 'nm_retribusi' => 'Retribusi Sewa Rumah Susun', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => NULL, 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '103'],
            ['id' => 93, 'kd_rekening' => '4120112', 'nm_retribusi' => 'Jasa pemeriksaan Laboratorium', 'dasar_hukum_pengenaan' => 'Perwal No. 37 Tahun 2017', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '105'],
            ['id' => 49, 'kd_rekening' => '4120151', 'nm_retribusi' => 'Retribusi Promosi Ikan Hias', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => NULL, 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '151'],
            ['id' => 28, 'kd_rekening' => '4120301', 'nm_retribusi' => 'Ijin Mendirikan Bangunan', 'dasar_hukum_pengenaan' => 'Perda No. 04 Tahun 2017', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 45, 'lv_kategori' => NULL, 'sub_kategori' => '3', 'kode_kategori' => '301'],
            ['id' => 112, 'kd_rekening' => '41201191', 'nm_retribusi' => 'Retribusi Pelayanan Parkir Di Tepi Jalan Umum (Motor)', 'dasar_hukum_pengenaan' => 'Perda nomor 10 tahun 2020', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '401'],
            ['id' => 113, 'kd_rekening' => '41201192', 'nm_retribusi' => 'Retribusi Pelayanan Parkir Di Tepi Jalan Umum (Sedan, Jeep, Minibus, Pickup dan Sejenisnya))', 'dasar_hukum_pengenaan' => 'Perda nomor 10 tahun 2020', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => '401'],
            ['id' => 116, 'kd_rekening' => '4120153', 'nm_retribusi' => 'Retribusi Pelayanan Pasar - Kios', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '0', 'karcis' => '0', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => NULL, 'kode_kategori' => NULL],
            ['id' => 115, 'kd_rekening' => '4120124', 'nm_retribusi' => 'Retribusi Pelayanan Sampah Pasar', 'dasar_hukum_pengenaan' => 'Perda No. 09 Tahun 2012', 'item' => '1', 'non_karcis' => '1', 'karcis' => '1', 'denda' => '0', 'fk_denda' => NULL, 'lv_kategori' => NULL, 'sub_kategori' => '201', 'kode_kategori' => NULL],
            ['id' => 5, 'kd_rekening' => '4120104', 'nm_retribusi' => 'Retribusi Pelayanan Kesehatan - Balai Pengobatan', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '0', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => NULL],
            ['id' => 7, 'kd_rekening' => '4120106', 'nm_retribusi' => 'Retribusi Pelayanan Kesehatan Tempat Pelayanan Kesehatan Lainnya yang Sejenis yang Dimiliki dan / atau Dikelola oleh Pemda', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '0', 'karcis' => '1', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '106'],
            ['id' => 8, 'kd_rekening' => '4120107', 'nm_retribusi' => 'Retribusi Pelayanan Persampahan / Kebersihan', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '201'],
            ['id' => 13, 'kd_rekening' => '4120125', 'nm_retribusi' => 'Retribusi PKB - Mobil Penumpang', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '601'],
            ['id' => 14, 'kd_rekening' => '4120127', 'nm_retribusi' => 'Retribusi PKB - Mobil Bus', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '602'],
            ['id' => 15, 'kd_rekening' => '4120128', 'nm_retribusi' => 'Retribusi PKB - Mobil Barang', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '603'],
            ['id' => 16, 'kd_rekening' => '4120137', 'nm_retribusi' => 'Retribusi Pelayanan Pemeriksaan dan / atau Pengujian Alat Pemadam Kebakaran', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '701'],
            ['id' => 17, 'kd_rekening' => '4120138', 'nm_retribusi' => 'Retribusi Alat Penanggulangan Kebakaran', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '138'],
            ['id' => 18, 'kd_rekening' => '4120147', 'nm_retribusi' => 'Retribusi Pengendalian Menara Telekomunikasi', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '130'],
            ['id' => 19, 'kd_rekening' => '4120148', 'nm_retribusi' => 'Retribusi Pelayanan Tera / Tera Ulang', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 43, 'lv_kategori' => NULL, 'sub_kategori' => '1', 'kode_kategori' => '110'],
            ['id' => 21, 'kd_rekening' => '41202', 'nm_retribusi' => 'Retribusi Jasa Usaha', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '0', 'non_karcis' => '0', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 44, 'lv_kategori' => '2', 'sub_kategori' => NULL, 'kode_kategori' => '791'],
            ['id' => 22, 'kd_rekening' => '4120201', 'nm_retribusi' => 'Retribusi Pemakaian Kekayaan Daerah - Penyewaan Tanah dan Bangunan', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 44, 'lv_kategori' => NULL, 'sub_kategori' => '2', 'kode_kategori' => '102'],
            ['id' => 23, 'kd_rekening' => '4120204', 'nm_retribusi' => 'Retribusi Pemakaian Kekayaan Daerah - Kendaraan Bermotor (kereta jenazah)', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 44, 'lv_kategori' => NULL, 'sub_kategori' => '2', 'kode_kategori' => '106'],
            ['id' => 24, 'kd_rekening' => '4120213', 'nm_retribusi' => 'Retribusi Terminal - Penyediaan Tempat Parkir Kendaraan Angkutan', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 44, 'lv_kategori' => NULL, 'sub_kategori' => '2', 'kode_kategori' => '213'],
            ['id' => 31, 'kd_rekening' => '4120305', 'nm_retribusi' => 'Izin Trayek Lokal Perpanjangan Kartu Pengawasan', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 47, 'lv_kategori' => NULL, 'sub_kategori' => '3', 'kode_kategori' => '306'],
            ['id' => 26, 'kd_rekening' => '41202701', 'nm_retribusi' => 'Retribusi Rumah Potong Hewan', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '1', 'denda' => '0', 'fk_denda' => 44, 'lv_kategori' => NULL, 'sub_kategori' => '2', 'kode_kategori' => '701'],
            ['id' => 25, 'kd_rekening' => '4120224', 'nm_retribusi' => 'Retribusi Pelayanan Tempat Olahraga', 'dasar_hukum_pengenaan' => 'Perda No. 01 Tahun 2024', 'item' => '1', 'non_karcis' => '1', 'karcis' => '0', 'denda' => '0', 'fk_denda' => 44, 'lv_kategori' => NULL, 'sub_kategori' => '2', 'kode_kategori' => '901'],
        ];
        foreach ($jenisretribusi as $jenisretribusi) {
            DB::table('jenis_retribusi')->insert($jenisretribusi);
        }
    }
}
