<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KelurahanSeeder extends Seeder
{
    public function run()
    {
        $kelurahan = [
            ['id' => 1, 'kd_kecamatan' => '120', 'kd_kelurahan' => '1', 'nm_kelurahan' => 'TOL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'kd_kecamatan' => '240', 'kd_kelurahan' => '2', 'nm_kelurahan' => 'CIPARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'kd_kecamatan' => '180', 'kd_kelurahan' => '3', 'nm_kelurahan' => 'MEKAR JAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'kd_kecamatan' => '120', 'kd_kelurahan' => '4', 'nm_kelurahan' => 'KAMPUNG LAMA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'kd_kecamatan' => '240', 'kd_kelurahan' => '5', 'nm_kelurahan' => 'LIANG BUAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'kd_kecamatan' => '90', 'kd_kelurahan' => '6', 'nm_kelurahan' => 'JANTUR BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'kd_kecamatan' => '90', 'kd_kelurahan' => '7', 'nm_kelurahan' => 'JANTUR SELATAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'kd_kecamatan' => '270', 'kd_kelurahan' => '8', 'nm_kelurahan' => 'BUKIT LAYANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'kd_kecamatan' => '270', 'kd_kelurahan' => '9', 'nm_kelurahan' => 'PERDANA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'kd_kecamatan' => '270', 'kd_kelurahan' => '10', 'nm_kelurahan' => 'MUAI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'kd_kecamatan' => '111', 'kd_kelurahan' => '11', 'nm_kelurahan' => 'TELUK BINGKAI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'kd_kecamatan' => '111', 'kd_kelurahan' => '12', 'nm_kelurahan' => 'KAHALA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'kd_kecamatan' => '111', 'kd_kelurahan' => '13', 'nm_kelurahan' => 'TUBUHAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'kd_kecamatan' => '111', 'kd_kelurahan' => '14', 'nm_kelurahan' => 'SEMAYANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'kd_kecamatan' => '111', 'kd_kelurahan' => '15', 'nm_kelurahan' => 'TELUK MUDA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'kd_kecamatan' => '111', 'kd_kelurahan' => '16', 'nm_kelurahan' => 'TUANA TUHA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'kd_kecamatan' => '120', 'kd_kelurahan' => '17', 'nm_kelurahan' => 'KARYA JAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'kd_kecamatan' => '120', 'kd_kelurahan' => '18', 'nm_kelurahan' => 'TANJUNG HARAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 19, 'kd_kecamatan' => '120', 'kd_kelurahan' => '19', 'nm_kelurahan' => 'WONOTIRTO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 20, 'kd_kecamatan' => '120', 'kd_kelurahan' => '20', 'nm_kelurahan' => 'SUNGAI SELUANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 21, 'kd_kecamatan' => '120', 'kd_kelurahan' => '21', 'nm_kelurahan' => 'RAWA JAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 22, 'kd_kecamatan' => '120', 'kd_kelurahan' => '22', 'nm_kelurahan' => 'SAMBOJA KUALA (INDUSTRI)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 23, 'kd_kecamatan' => '120', 'kd_kelurahan' => '23', 'nm_kelurahan' => 'SAMBOJA KUALA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 24, 'kd_kecamatan' => '120', 'kd_kelurahan' => '24', 'nm_kelurahan' => 'SANIPAH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 25, 'kd_kecamatan' => '120', 'kd_kelurahan' => '25', 'nm_kelurahan' => 'HANDIL BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 26, 'kd_kecamatan' => '120', 'kd_kelurahan' => '26', 'nm_kelurahan' => 'MUARA SEMBILANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 27, 'kd_kecamatan' => '120', 'kd_kelurahan' => '27', 'nm_kelurahan' => 'BUKIT RAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 28, 'kd_kecamatan' => '130', 'kd_kelurahan' => '28', 'nm_kelurahan' => 'BAKUNGAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 29, 'kd_kecamatan' => '130', 'kd_kelurahan' => '29', 'nm_kelurahan' => 'LOA DURI ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 30, 'kd_kecamatan' => '130', 'kd_kelurahan' => '30', 'nm_kelurahan' => 'LOA JANAN ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 31, 'kd_kecamatan' => '130', 'kd_kelurahan' => '31', 'nm_kelurahan' => 'PURWAJAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 32, 'kd_kecamatan' => '130', 'kd_kelurahan' => '32', 'nm_kelurahan' => 'TANI BHAKTI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 33, 'kd_kecamatan' => '130', 'kd_kelurahan' => '33', 'nm_kelurahan' => 'BATUAH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 34, 'kd_kecamatan' => '140', 'kd_kelurahan' => '34', 'nm_kelurahan' => 'JAWA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 35, 'kd_kecamatan' => '140', 'kd_kelurahan' => '35', 'nm_kelurahan' => 'PENDINGIN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 36, 'kd_kecamatan' => '140', 'kd_kelurahan' => '36', 'nm_kelurahan' => 'SANGA-SANGA DALAM', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 37, 'kd_kecamatan' => '140', 'kd_kelurahan' => '37', 'nm_kelurahan' => 'SARI JAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 38, 'kd_kecamatan' => '140', 'kd_kelurahan' => '38', 'nm_kelurahan' => 'SANGA SANGA MUARA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 39, 'kd_kecamatan' => '150', 'kd_kelurahan' => '39', 'nm_kelurahan' => 'SEPATIN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 40, 'kd_kecamatan' => '150', 'kd_kelurahan' => '40', 'nm_kelurahan' => 'MUARA PANTUAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 41, 'kd_kecamatan' => '150', 'kd_kelurahan' => '41', 'nm_kelurahan' => 'TANI BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 42, 'kd_kecamatan' => '150', 'kd_kelurahan' => '42', 'nm_kelurahan' => 'KUTAI LAMA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 43, 'kd_kecamatan' => '150', 'kd_kelurahan' => '43', 'nm_kelurahan' => 'ANGGANA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 44, 'kd_kecamatan' => '150', 'kd_kelurahan' => '44', 'nm_kelurahan' => 'SUNGAI MERIAM', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 45, 'kd_kecamatan' => '150', 'kd_kelurahan' => '45', 'nm_kelurahan' => 'SIDOMULYO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 46, 'kd_kecamatan' => '150', 'kd_kelurahan' => '46', 'nm_kelurahan' => 'ANGGANA (INDUSTRI)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 47, 'kd_kecamatan' => '150', 'kd_kelurahan' => '47', 'nm_kelurahan' => 'SEI MERIAM (INDUSTRI)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 48, 'kd_kecamatan' => '160', 'kd_kelurahan' => '48', 'nm_kelurahan' => 'SELIKI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 49, 'kd_kecamatan' => '160', 'kd_kelurahan' => '49', 'nm_kelurahan' => 'SALO PALAY', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 50, 'kd_kecamatan' => '160', 'kd_kelurahan' => '50', 'nm_kelurahan' => 'MUARA BADAK ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 51, 'kd_kecamatan' => '160', 'kd_kelurahan' => '51', 'nm_kelurahan' => 'MUARA BADAK ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 52, 'kd_kecamatan' => '160', 'kd_kelurahan' => '52', 'nm_kelurahan' => 'TANJUNG LIMAU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 53, 'kd_kecamatan' => '161', 'kd_kelurahan' => '53', 'nm_kelurahan' => 'SEBUNTAL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 54, 'kd_kecamatan' => '161', 'kd_kelurahan' => '54', 'nm_kelurahan' => 'SANTAN ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 55, 'kd_kecamatan' => '161', 'kd_kelurahan' => '55', 'nm_kelurahan' => 'SANTAN TENGAH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 56, 'kd_kecamatan' => '161', 'kd_kelurahan' => '56', 'nm_kelurahan' => 'SANTAN ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 57, 'kd_kecamatan' => '161', 'kd_kelurahan' => '57', 'nm_kelurahan' => 'KERSIK', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 58, 'kd_kecamatan' => '170', 'kd_kelurahan' => '58', 'nm_kelurahan' => 'JAHAB', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 59, 'kd_kecamatan' => '170', 'kd_kelurahan' => '59', 'nm_kelurahan' => 'TIMBAU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 60, 'kd_kecamatan' => '170', 'kd_kelurahan' => '60', 'nm_kelurahan' => 'BUKIT BIRU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 61, 'kd_kecamatan' => '170', 'kd_kelurahan' => '61', 'nm_kelurahan' => 'MELAYU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 62, 'kd_kecamatan' => '170', 'kd_kelurahan' => '62', 'nm_kelurahan' => 'LOA IPUH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 63, 'kd_kecamatan' => '170', 'kd_kelurahan' => '63', 'nm_kelurahan' => 'MALUHU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 64, 'kd_kecamatan' => '170', 'kd_kelurahan' => '64', 'nm_kelurahan' => 'PANJI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 65, 'kd_kecamatan' => '170', 'kd_kelurahan' => '65', 'nm_kelurahan' => 'SUKARAME', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 66, 'kd_kecamatan' => '170', 'kd_kelurahan' => '66', 'nm_kelurahan' => 'BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 67, 'kd_kecamatan' => '170', 'kd_kelurahan' => '67', 'nm_kelurahan' => 'MANGKURAWANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 68, 'kd_kecamatan' => '170', 'kd_kelurahan' => '68', 'nm_kelurahan' => 'LOA TEBU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 69, 'kd_kecamatan' => '171', 'kd_kelurahan' => '69', 'nm_kelurahan' => 'MANUNGGAL JAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 70, 'kd_kecamatan' => '171', 'kd_kelurahan' => '70', 'nm_kelurahan' => 'BUKIT RAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 71, 'kd_kecamatan' => '171', 'kd_kelurahan' => '71', 'nm_kelurahan' => 'EMBALUT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 72, 'kd_kecamatan' => '171', 'kd_kelurahan' => '72', 'nm_kelurahan' => 'BANGUN REJO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 73, 'kd_kecamatan' => '171', 'kd_kelurahan' => '73', 'nm_kelurahan' => 'KERTA BUANA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 74, 'kd_kecamatan' => '171', 'kd_kelurahan' => '74', 'nm_kelurahan' => 'SEPARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 75, 'kd_kecamatan' => '171', 'kd_kelurahan' => '75', 'nm_kelurahan' => 'BUKIT PARIAMAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 76, 'kd_kecamatan' => '171', 'kd_kelurahan' => '76', 'nm_kelurahan' => 'BUANA JAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 77, 'kd_kecamatan' => '171', 'kd_kelurahan' => '77', 'nm_kelurahan' => 'MULAWARMAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 78, 'kd_kecamatan' => '171', 'kd_kelurahan' => '78', 'nm_kelurahan' => 'LOA ULUNG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 79, 'kd_kecamatan' => '171', 'kd_kelurahan' => '79', 'nm_kelurahan' => 'LOA RAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 80, 'kd_kecamatan' => '171', 'kd_kelurahan' => '80', 'nm_kelurahan' => 'PERJIWA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 81, 'kd_kecamatan' => '171', 'kd_kelurahan' => '81', 'nm_kelurahan' => 'TELUK DALAM', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 82, 'kd_kecamatan' => '171', 'kd_kelurahan' => '82', 'nm_kelurahan' => 'LOA LEPU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 83, 'kd_kecamatan' => '171', 'kd_kelurahan' => '83', 'nm_kelurahan' => 'LOA PARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 84, 'kd_kecamatan' => '180', 'kd_kelurahan' => '84', 'nm_kelurahan' => 'SELERONG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 85, 'kd_kecamatan' => '180', 'kd_kelurahan' => '85', 'nm_kelurahan' => 'TANJUNG HARAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 86, 'kd_kecamatan' => '180', 'kd_kelurahan' => '86', 'nm_kelurahan' => 'BELORO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 87, 'kd_kecamatan' => '180', 'kd_kelurahan' => '87', 'nm_kelurahan' => 'SEBULU ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 88, 'kd_kecamatan' => '180', 'kd_kelurahan' => '88', 'nm_kelurahan' => 'MANUNGGAL DAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 89, 'kd_kecamatan' => '180', 'kd_kelurahan' => '89', 'nm_kelurahan' => 'SUMBERSARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 90, 'kd_kecamatan' => '180', 'kd_kelurahan' => '90', 'nm_kelurahan' => 'SEBULU ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 91, 'kd_kecamatan' => '180', 'kd_kelurahan' => '91', 'nm_kelurahan' => 'SEGIHAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 92, 'kd_kecamatan' => '180', 'kd_kelurahan' => '92', 'nm_kelurahan' => 'GIRI AGUNG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 93, 'kd_kecamatan' => '240', 'kd_kelurahan' => '93', 'nm_kelurahan' => 'TERATAK', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 94, 'kd_kecamatan' => '240', 'kd_kelurahan' => '94', 'nm_kelurahan' => 'BENUA PUHUN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 95, 'kd_kecamatan' => '240', 'kd_kelurahan' => '95', 'nm_kelurahan' => 'RANTAU HEMPANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 96, 'kd_kecamatan' => '240', 'kd_kelurahan' => '96', 'nm_kelurahan' => 'MUARA KAMAN ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 97, 'kd_kecamatan' => '240', 'kd_kelurahan' => '97', 'nm_kelurahan' => 'MUARA KAMAN ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 98, 'kd_kecamatan' => '240', 'kd_kelurahan' => '98', 'nm_kelurahan' => 'MUARA SIRAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 99, 'kd_kecamatan' => '240', 'kd_kelurahan' => '99', 'nm_kelurahan' => 'TUNJUNGAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 100, 'kd_kecamatan' => '240', 'kd_kelurahan' => '100', 'nm_kelurahan' => 'SABINTULUNG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 101, 'kd_kecamatan' => '240', 'kd_kelurahan' => '101', 'nm_kelurahan' => 'PANCA JAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 102, 'kd_kecamatan' => '240', 'kd_kelurahan' => '102', 'nm_kelurahan' => 'SIDOMUKTI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 103, 'kd_kecamatan' => '240', 'kd_kelurahan' => '103', 'nm_kelurahan' => 'SEDULANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 104, 'kd_kecamatan' => '240', 'kd_kelurahan' => '104', 'nm_kelurahan' => 'MENAMANG KANAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 105, 'kd_kecamatan' => '240', 'kd_kelurahan' => '105', 'nm_kelurahan' => 'MENAMANG KIRI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 106, 'kd_kecamatan' => '250', 'kd_kelurahan' => '106', 'nm_kelurahan' => 'KOTA BANGUN ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 107, 'kd_kecamatan' => '250', 'kd_kelurahan' => '107', 'nm_kelurahan' => 'LOLENG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 108, 'kd_kecamatan' => '250', 'kd_kelurahan' => '108', 'nm_kelurahan' => 'KOTA BANGUN ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 109, 'kd_kecamatan' => '250', 'kd_kelurahan' => '109', 'nm_kelurahan' => 'LIANG ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 110, 'kd_kecamatan' => '250', 'kd_kelurahan' => '110', 'nm_kelurahan' => 'MUHURAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 111, 'kd_kecamatan' => '250', 'kd_kelurahan' => '111', 'nm_kelurahan' => 'PELA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 112, 'kd_kecamatan' => '251', 'kd_kelurahan' => '112', 'nm_kelurahan' => 'MUARA WIS', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 113, 'kd_kecamatan' => '251', 'kd_kelurahan' => '113', 'nm_kelurahan' => 'SEBEMBAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 114, 'kd_kecamatan' => '251', 'kd_kelurahan' => '114', 'nm_kelurahan' => 'MELINTANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 115, 'kd_kecamatan' => '251', 'kd_kelurahan' => '115', 'nm_kelurahan' => 'LEBAQ MANTAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 116, 'kd_kecamatan' => '251', 'kd_kelurahan' => '116', 'nm_kelurahan' => 'LEBAQ CILONG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 117, 'kd_kecamatan' => '270', 'kd_kelurahan' => '117', 'nm_kelurahan' => 'GENTING TANAH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 118, 'kd_kecamatan' => '270', 'kd_kelurahan' => '118', 'nm_kelurahan' => 'LOA SAKOH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 119, 'kd_kecamatan' => '270', 'kd_kelurahan' => '119', 'nm_kelurahan' => 'HAMBAU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 120, 'kd_kecamatan' => '270', 'kd_kelurahan' => '120', 'nm_kelurahan' => 'KEMBANG JANGGUT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 121, 'kd_kecamatan' => '270', 'kd_kelurahan' => '121', 'nm_kelurahan' => 'KELEKAT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 122, 'kd_kecamatan' => '270', 'kd_kelurahan' => '122', 'nm_kelurahan' => 'PULAU PINANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 123, 'kd_kecamatan' => '270', 'kd_kelurahan' => '123', 'nm_kelurahan' => 'LONG BELEH HALOK', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 124, 'kd_kecamatan' => '270', 'kd_kelurahan' => '124', 'nm_kelurahan' => 'LONG BELEH MODANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 125, 'kd_kecamatan' => '280', 'kd_kelurahan' => '125', 'nm_kelurahan' => 'GUNUNG SARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 126, 'kd_kecamatan' => '280', 'kd_kelurahan' => '126', 'nm_kelurahan' => 'LONG LALANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 127, 'kd_kecamatan' => '280', 'kd_kelurahan' => '127', 'nm_kelurahan' => 'MUARA RITAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 128, 'kd_kecamatan' => '280', 'kd_kelurahan' => '128', 'nm_kelurahan' => 'RITAN BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 129, 'kd_kecamatan' => '280', 'kd_kelurahan' => '129', 'nm_kelurahan' => 'UMAQ DIAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 130, 'kd_kecamatan' => '280', 'kd_kelurahan' => '130', 'nm_kelurahan' => 'MUARA PEDOHON', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 131, 'kd_kecamatan' => '280', 'kd_kelurahan' => '131', 'nm_kelurahan' => 'UMAQ TUKUNG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 132, 'kd_kecamatan' => '280', 'kd_kelurahan' => '132', 'nm_kelurahan' => 'B A R U', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 133, 'kd_kecamatan' => '280', 'kd_kelurahan' => '133', 'nm_kelurahan' => 'BILA TALANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 134, 'kd_kecamatan' => '280', 'kd_kelurahan' => '134', 'nm_kelurahan' => 'UMAQ BEKUAY', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 135, 'kd_kecamatan' => '280', 'kd_kelurahan' => '135', 'nm_kelurahan' => 'SIDOMULYO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 136, 'kd_kecamatan' => '280', 'kd_kelurahan' => '136', 'nm_kelurahan' => 'MUARA TIQ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 137, 'kd_kecamatan' => '280', 'kd_kelurahan' => '137', 'nm_kelurahan' => 'TABANG LAMA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 138, 'kd_kecamatan' => '280', 'kd_kelurahan' => '138', 'nm_kelurahan' => 'MUARA SALUNG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 139, 'kd_kecamatan' => '280', 'kd_kelurahan' => '139', 'nm_kelurahan' => 'MUARA KEBAQ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 140, 'kd_kecamatan' => '280', 'kd_kelurahan' => '140', 'nm_kelurahan' => 'MUARA BELINAU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 141, 'kd_kecamatan' => '280', 'kd_kelurahan' => '141', 'nm_kelurahan' => 'MUARA TUBOQ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 142, 'kd_kecamatan' => '280', 'kd_kelurahan' => '142', 'nm_kelurahan' => 'KARANGAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 143, 'kd_kecamatan' => '280', 'kd_kelurahan' => '143', 'nm_kelurahan' => 'BULUQ SEN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 144, 'kd_kecamatan' => '280', 'kd_kelurahan' => '144', 'nm_kelurahan' => 'MUARA RITAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 145, 'kd_kecamatan' => '171', 'kd_kelurahan' => '145', 'nm_kelurahan' => 'SUKAMAJU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 146, 'kd_kecamatan' => '240', 'kd_kelurahan' => '146', 'nm_kelurahan' => 'LEBAHO ULAQ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 147, 'kd_kecamatan' => '180', 'kd_kelurahan' => '147', 'nm_kelurahan' => 'SEBULU MODERN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 148, 'kd_kecamatan' => '160', 'kd_kelurahan' => '148', 'nm_kelurahan' => 'SUKA DAMAI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 149, 'kd_kecamatan' => '160', 'kd_kelurahan' => '149', 'nm_kelurahan' => 'TANAH DATAR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 150, 'kd_kecamatan' => '180', 'kd_kelurahan' => '150', 'nm_kelurahan' => 'SENONI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 151, 'kd_kecamatan' => '240', 'kd_kelurahan' => '151', 'nm_kelurahan' => 'BUNGA JADI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 152, 'kd_kecamatan' => '90', 'kd_kelurahan' => '152', 'nm_kelurahan' => 'TANJUNG BATUQ HARAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 153, 'kd_kecamatan' => '170', 'kd_kelurahan' => '153', 'nm_kelurahan' => 'RAPAK LAMBUR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 154, 'kd_kecamatan' => '170', 'kd_kelurahan' => '154', 'nm_kelurahan' => 'LOA IPUH DARAT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 155, 'kd_kecamatan' => '161', 'kd_kelurahan' => '155', 'nm_kelurahan' => 'PRANGAT SELATAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 156, 'kd_kecamatan' => '161', 'kd_kelurahan' => '156', 'nm_kelurahan' => 'MAKARTI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 157, 'kd_kecamatan' => '161', 'kd_kelurahan' => '157', 'nm_kelurahan' => 'SEMANGKO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 158, 'kd_kecamatan' => '250', 'kd_kelurahan' => '158', 'nm_kelurahan' => 'SEBELIMBINGAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 159, 'kd_kecamatan' => '250', 'kd_kelurahan' => '159', 'nm_kelurahan' => 'KOTA BANGUN SEBERANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 160, 'kd_kecamatan' => '250', 'kd_kelurahan' => '160', 'nm_kelurahan' => 'LIANG ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 161, 'kd_kecamatan' => '130', 'kd_kelurahan' => '161', 'nm_kelurahan' => 'LOA DURI ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 162, 'kd_kecamatan' => '130', 'kd_kelurahan' => '162', 'nm_kelurahan' => 'TANI HARAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 163, 'kd_kecamatan' => '160', 'kd_kelurahan' => '163', 'nm_kelurahan' => 'BADAK BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 164, 'kd_kecamatan' => '171', 'kd_kelurahan' => '164', 'nm_kelurahan' => 'KARANG TUNGGAL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 165, 'kd_kecamatan' => '130', 'kd_kelurahan' => '165', 'nm_kelurahan' => 'JAHUQ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 166, 'kd_kecamatan' => '160', 'kd_kelurahan' => '166', 'nm_kelurahan' => 'BATU-BATU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 167, 'kd_kecamatan' => '160', 'kd_kelurahan' => '167', 'nm_kelurahan' => 'BADAK MEKAR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 168, 'kd_kecamatan' => '120', 'kd_kelurahan' => '168', 'nm_kelurahan' => 'TELUK PEMEDAS', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 169, 'kd_kecamatan' => '160', 'kd_kelurahan' => '169', 'nm_kelurahan' => 'SALO CELLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 170, 'kd_kecamatan' => '160', 'kd_kelurahan' => '170', 'nm_kelurahan' => 'SUNGAI BAWANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 171, 'kd_kecamatan' => '240', 'kd_kelurahan' => '171', 'nm_kelurahan' => 'KUPANG BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 172, 'kd_kecamatan' => '161', 'kd_kelurahan' => '172', 'nm_kelurahan' => 'PRANGAT BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 173, 'kd_kecamatan' => '161', 'kd_kelurahan' => '173', 'nm_kelurahan' => 'BUNGA PUTIH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 174, 'kd_kecamatan' => '240', 'kd_kelurahan' => '174', 'nm_kelurahan' => 'PUAN CEPAK', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 175, 'kd_kecamatan' => '100', 'kd_kelurahan' => '175', 'nm_kelurahan' => 'JONGKANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 176, 'kd_kecamatan' => '100', 'kd_kelurahan' => '176', 'nm_kelurahan' => 'JEMBAYAN DALAM', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 177, 'kd_kecamatan' => '110', 'kd_kelurahan' => '177', 'nm_kelurahan' => 'MUARA JAWA PESISIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 178, 'kd_kecamatan' => '250', 'kd_kelurahan' => '178', 'nm_kelurahan' => 'KEDANG MURUNG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 179, 'kd_kecamatan' => '100', 'kd_kelurahan' => '179', 'nm_kelurahan' => 'DATA RAWA LOA GAGAK', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 180, 'kd_kecamatan' => '171', 'kd_kelurahan' => '180', 'nm_kelurahan' => 'TANJUNG BATU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 181, 'kd_kecamatan' => '240', 'kd_kelurahan' => '181', 'nm_kelurahan' => 'BUKIT JERING', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 182, 'kd_kecamatan' => '150', 'kd_kelurahan' => '182', 'nm_kelurahan' => 'HANDIL TERUSAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 183, 'kd_kecamatan' => '90', 'kd_kelurahan' => '183', 'nm_kelurahan' => 'PULAU HARAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 184, 'kd_kecamatan' => '161', 'kd_kelurahan' => '184', 'nm_kelurahan' => 'SAMBERA BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 185, 'kd_kecamatan' => '100', 'kd_kelurahan' => '185', 'nm_kelurahan' => 'LUNG ANAI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 186, 'kd_kecamatan' => '160', 'kd_kelurahan' => '186', 'nm_kelurahan' => 'GAS ALAM BADAK 1', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 187, 'kd_kecamatan' => '121', 'kd_kelurahan' => '187', 'nm_kelurahan' => 'KARYA MERDEKA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 188, 'kd_kecamatan' => '90', 'kd_kelurahan' => '188', 'nm_kelurahan' => 'PERIAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 189, 'kd_kecamatan' => '90', 'kd_kelurahan' => '189', 'nm_kelurahan' => 'MUARA LEKA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 190, 'kd_kecamatan' => '90', 'kd_kelurahan' => '190', 'nm_kelurahan' => 'MUARA ALOH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 191, 'kd_kecamatan' => '90', 'kd_kelurahan' => '191', 'nm_kelurahan' => 'JANTUR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 192, 'kd_kecamatan' => '90', 'kd_kelurahan' => '192', 'nm_kelurahan' => 'BATUQ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 193, 'kd_kecamatan' => '90', 'kd_kelurahan' => '193', 'nm_kelurahan' => 'REBAQ RINDING', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 194, 'kd_kecamatan' => '90', 'kd_kelurahan' => '194', 'nm_kelurahan' => 'MUARA MUNTAI ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 195, 'kd_kecamatan' => '90', 'kd_kelurahan' => '195', 'nm_kelurahan' => 'MUARA MUNTAI ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 196, 'kd_kecamatan' => '90', 'kd_kelurahan' => '196', 'nm_kelurahan' => 'KAYU BATU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 197, 'kd_kecamatan' => '100', 'kd_kelurahan' => '197', 'nm_kelurahan' => 'JONGGON DESA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 198, 'kd_kecamatan' => '100', 'kd_kelurahan' => '198', 'nm_kelurahan' => 'SUNGAI PAYANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 199, 'kd_kecamatan' => '100', 'kd_kelurahan' => '199', 'nm_kelurahan' => 'JEMBAYAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 200, 'kd_kecamatan' => '100', 'kd_kelurahan' => '200', 'nm_kelurahan' => 'PONORAGAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 201, 'kd_kecamatan' => '100', 'kd_kelurahan' => '201', 'nm_kelurahan' => 'LOH SUMBER', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 202, 'kd_kecamatan' => '100', 'kd_kelurahan' => '202', 'nm_kelurahan' => 'LOA KULU KOTA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 203, 'kd_kecamatan' => '100', 'kd_kelurahan' => '203', 'nm_kelurahan' => 'REMPANGA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 204, 'kd_kecamatan' => '100', 'kd_kelurahan' => '204', 'nm_kelurahan' => 'JEMBAYAN (INDUSTRI)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 205, 'kd_kecamatan' => '100', 'kd_kelurahan' => '205', 'nm_kelurahan' => 'LOA KULU (INDUSTRI)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 206, 'kd_kecamatan' => '100', 'kd_kelurahan' => '206', 'nm_kelurahan' => 'MARGASARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 207, 'kd_kecamatan' => '100', 'kd_kelurahan' => '207', 'nm_kelurahan' => 'JEMBAYAN TENGAH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 208, 'kd_kecamatan' => '100', 'kd_kelurahan' => '208', 'nm_kelurahan' => 'TANJUNG LAUNG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 209, 'kd_kecamatan' => '100', 'kd_kelurahan' => '209', 'nm_kelurahan' => 'JONGGON JAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 210, 'kd_kecamatan' => '100', 'kd_kelurahan' => '210', 'nm_kelurahan' => 'MARGAHAYU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 211, 'kd_kecamatan' => '110', 'kd_kelurahan' => '211', 'nm_kelurahan' => 'MUARA JAWA ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 212, 'kd_kecamatan' => '110', 'kd_kelurahan' => '212', 'nm_kelurahan' => 'MUARA JAWA TENGAH', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 213, 'kd_kecamatan' => '110', 'kd_kelurahan' => '213', 'nm_kelurahan' => 'MUARA JAWA ULU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 214, 'kd_kecamatan' => '110', 'kd_kelurahan' => '214', 'nm_kelurahan' => 'MUARA KEMBANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 215, 'kd_kecamatan' => '110', 'kd_kelurahan' => '215', 'nm_kelurahan' => 'TAMA POLE', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 216, 'kd_kecamatan' => '110', 'kd_kelurahan' => '216', 'nm_kelurahan' => 'DONDANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 217, 'kd_kecamatan' => '110', 'kd_kelurahan' => '217', 'nm_kelurahan' => 'TELUK DALAM', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 218, 'kd_kecamatan' => '110', 'kd_kelurahan' => '218', 'nm_kelurahan' => 'MUARA JAWA ILIR (INDUSTRI)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 219, 'kd_kecamatan' => '110', 'kd_kelurahan' => '219', 'nm_kelurahan' => 'MUARA JAWA ULU (INDUSTRI)', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 220, 'kd_kecamatan' => '111', 'kd_kelurahan' => '220', 'nm_kelurahan' => 'LAMIN TELIHAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 221, 'kd_kecamatan' => '111', 'kd_kelurahan' => '221', 'nm_kelurahan' => 'LAMIN PULUT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 222, 'kd_kecamatan' => '100', 'kd_kelurahan' => '222', 'nm_kelurahan' => 'SUMBER SARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 223, 'kd_kecamatan' => '100', 'kd_kelurahan' => '223', 'nm_kelurahan' => 'SEPAKAT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 224, 'kd_kecamatan' => '180', 'kd_kelurahan' => '224', 'nm_kelurahan' => 'LEKAQ KIDAU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 225, 'kd_kecamatan' => '251', 'kd_kelurahan' => '225', 'nm_kelurahan' => 'MUARA ENGGELAM', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 226, 'kd_kecamatan' => '121', 'kd_kelurahan' => '226', 'nm_kelurahan' => 'BUKIT MERDEKA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 227, 'kd_kecamatan' => '121', 'kd_kelurahan' => '227', 'nm_kelurahan' => 'SUNGAI MERDEKA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 228, 'kd_kecamatan' => '121', 'kd_kelurahan' => '228', 'nm_kelurahan' => 'TANI BAKTI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 229, 'kd_kecamatan' => '121', 'kd_kelurahan' => '229', 'nm_kelurahan' => 'AMBORAWANG DARAT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 230, 'kd_kecamatan' => '121', 'kd_kelurahan' => '230', 'nm_kelurahan' => 'ARGOSARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 231, 'kd_kecamatan' => '121', 'kd_kelurahan' => '231', 'nm_kelurahan' => 'SALOK API DARAT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 232, 'kd_kecamatan' => '121', 'kd_kelurahan' => '232', 'nm_kelurahan' => 'SALOK API LAUT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 233, 'kd_kecamatan' => '121', 'kd_kelurahan' => '233', 'nm_kelurahan' => 'AMBORAWANG LAUT', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 234, 'kd_kecamatan' => '121', 'kd_kelurahan' => '234', 'nm_kelurahan' => 'MARGO MULYO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 235, 'kd_kecamatan' => '170', 'kd_kelurahan' => '235', 'nm_kelurahan' => 'BENDANG RAYA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 236, 'kd_kecamatan' => '111', 'kd_kelurahan' => '236', 'nm_kelurahan' => 'KAHALA ILIR', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 237, 'kd_kecamatan' => '280', 'kd_kelurahan' => '237', 'nm_kelurahan' => 'TUKUNG RITAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 238, 'kd_kecamatan' => '180', 'kd_kelurahan' => '238', 'nm_kelurahan' => 'SANGGULAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 239, 'kd_kecamatan' => '252', 'kd_kelurahan' => '239', 'nm_kelurahan' => 'KEDANG IPIL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 240, 'kd_kecamatan' => '252', 'kd_kelurahan' => '240', 'nm_kelurahan' => 'SEDULANG', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 241, 'kd_kecamatan' => '252', 'kd_kelurahan' => '241', 'nm_kelurahan' => 'BENUA BARU', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 242, 'kd_kecamatan' => '252', 'kd_kelurahan' => '242', 'nm_kelurahan' => 'KOTA BANGUN I', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 243, 'kd_kecamatan' => '252', 'kd_kelurahan' => '243', 'nm_kelurahan' => 'KOTA BANGUN II', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 244, 'kd_kecamatan' => '252', 'kd_kelurahan' => '244', 'nm_kelurahan' => 'KOTA BANGUN III', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 245, 'kd_kecamatan' => '252', 'kd_kelurahan' => '245', 'nm_kelurahan' => 'SUMBER SARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 246, 'kd_kecamatan' => '252', 'kd_kelurahan' => '246', 'nm_kelurahan' => 'SARINADI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 247, 'kd_kecamatan' => '252', 'kd_kelurahan' => '247', 'nm_kelurahan' => 'SUKA BUMI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 248, 'kd_kecamatan' => '252', 'kd_kelurahan' => '248', 'nm_kelurahan' => 'WONO SARI', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 249, 'kd_kecamatan' => '120', 'kd_kelurahan' => '249', 'nm_kelurahan' => 'HANDIL BARU DARAT', 'created_at' => now(), 'updated_at' => now()],
        ];

        foreach ($kelurahan as $kelurahan) {
            DB::table('kelurahan')->insert($kelurahan);
        }
    }
}
